name: Update and deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: echo "policy aliases"

# TODO
# install hugo
# log in to azure
# run script
# commit and push
# deploy