name: Update Theme

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/update-theme.yml
      - src/update-theme.sh

  schedule:
    - cron: "0 2 * * 1" # every monday 02 AM UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for theme updates
        id: update
        run: ./src/update-theme.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'build(deps): update hugo-geekdoc theme to ${{ steps.update.outputs.VERSION }}'
          branch: build/theme-update
          delete-branch: true
          title: 'build(deps): update hugo-geekdoc theme to ${{ steps.update.outputs.VERSION }}'
          body: |
            - Updated theme to https://github.com/thegeeklab/hugo-geekdoc/releases/tag/${{ steps.update.outputs.VERSION }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            dependencies
          assignees: matsest
